language: python
python:
  - "2.7"
sudo: required
cache: pip
branches:
  only:
    - master
install:
  - cd pelican-themes/fles && npm install && cd -
  - pip install -r requirements.txt
script:
  - make publish github
before_script:
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${NICK}
after_script:
  - make purge